source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'GrowingImageView_Example', :exclusive => true do
  pod "GrowingImageView", :path => "../"
end

target 'GrowingImageView_Tests', :exclusive => true do
  pod "GrowingImageView", :path => "../"

  
end
